### PR TITLE
Fix dependencies for iog-full flavor

### PR DESCRIPTION
**Pull request by sgillespie**
* Use correct variant of optional/optionals
 * Clean up formatting

### CODE REVIEW

**Review by angerman — APPROVED** [review]
That's weird.

**Comment by andreabedini** [comment]
Also, I might be wrong but I don't think we need to use getDev for buildInputs, as they are [implied](https://github.com/hsjobeki/nixpkgs/blob/migrate-doc-comments/pkgs/stdenv/generic/make-derivation.nix#L304-L317).

**Comment by andreabedini** [comment]
Right above there is
```
with pkgs; [ (pkgs.pkg-config or pkgconfig) ... ]
```
I find it hard to read. Is that supposed to mean `pkgs.pkg-config or pkgs.pkgconfig`?

**Comment by andreabedini** [comment]
This is my take:

```nix
  buildInputs =
    let
      inherit (pkgs) lib stdenv;
      inherit (lib) attrValues optional optionals;
    in
    [
      wrapped-cabal
      fixup-nix-deps
      compiler
      # for libstdc++; ghc not being able to find this properly is bad,
      # it _should_ probably call out to a g++ or clang++ but doesn't.
      stdenv.cc.cc.lib
    ]
    ++ (with pkgs; [
      openssl
      pcre
      pkg-config
      zlib
    ])
    ++ optional stdenv.hostPlatform.isLinux pkgs.systemd
    ++ optionals withIOG (
      with pkgs;
      [
        cddl
        cbor-diag
        gh
        jq
        yq-go
        libblst
        libsodium-vrf
        secp256k1
        icu
      ]
      ++ optionals withIOGFull (
        [ postgresql ] # for db-sync
        ++ optional stdenv.hostPlatform.isAarch64 R
      )
    )
    ++ attrValues haskell-tools;
```

**Comment by sgillespie** [comment]
> `optional :: bool -> a -> [a]` so isn't there an extra list in both the new and the old version?
> 
> ```
> ++ map pkgs.lib.getDev (with pkgs; [ libblst libsodium-vrf secp256k1 icu ]) # :: [Derivation]
> ++ lib.optional withIOGFull
>    (map pkgs.lib.getDev
>      (with pkgs; [ (if stdenv.hostPlatform.isAarch64 then null else R) postgresql ]) # :: [Derivation]
>    ) # :: [[Derivation]
> ```
> 
> Maybe `optionals` is what should use?

Ah, you're right. I was mistakenly looking at the docs for `optionals`

**Comment by sgillespie** [comment]
> Right above there is
> 
> ```
> with pkgs; [ (pkgs.pkg-config or pkgconfig) ... ]
> ```
> 
> I find it hard to read. Is that supposed to mean `pkgs.pkg-config or pkgs.pkgconfig`? Edit: It looks like `pkg-config` is in nixpkgs but `pkgconfig` is not. Why do we need this?

IIRC `pkgconfig` was removed recently-ish. I don't see why we still need `pkgconfig` in here.

**Pull request merged**
