### PR TITLE
Add Windows Cross Compilers

### PR DESCRIPTION
**Pull request by hamishmack**

### CODE REVIEW

**Review by angerman — COMMENTED** [review]
I don't think our Darwin -> Windows cross toolchain works.

**Comment by hamishmack** [comment]
> I don't think our Darwin -> Windows cross toolchain works.

It has in the past.  I think current mix of wine/mingw/ghc 9.6/darwin/nixpkgs is broken though.

**Comment by angerman** [comment]
> > I don't think our Darwin -> Windows cross toolchain works.
> 
> It has in the past. I think current mix of wine/mingw/ghc 9.6/darwin/nixpkgs is broken though.

I believe it's been broken, or flake for quite some time :( So for now I'd just ignore it.

**Comment by angerman** [comment]
So I've added a bunch of changes:
- turned the build/run into a reusable workflow, this allows us to get around the annoying double matrix.
- fixed the ` windows-latest` (leading space); GH runners are awesome in not showing you the leading space, and just waiting forever for a runner to show up with a leading space 🤦 
- Added an inspect phase. This shows us for dynamic linux:
  ```
  /nix/store/c35hf8g5b9vksadym9dbjrd6p2y11m8h-glibc-2.35-224/lib/ld-linux-x86-64.so.2
  libgmp.so.10
  libc.so.6
  libm.so.6
  librt.so.1
  libdl.so.2
  libffi.so.8
  libnuma.so.1
  ```
  So this will likely never work. We _can_ use `patchelf` to change the interpreter to `/lib/ld-linux.so.2` for unbuntu
  ```
  patchelf --set-interpreter /lib/ld-linux.so.2 bin/test
  ```
  we'd also need to copy all the dynamic libraries alongside and package them as well. (or maybe we can remove them; not sure if they are really used?)
- [!] we need to embed a git hash into the devx shell. Currently it's impossible to tell from which revision the specific shell was built.

**Comment by angerman** [comment]
I've extracted most of the cleanup into #49

**Comment by angerman** [comment]
somehow the changed base did not work properly.

**Comment by angerman** [comment]
git diff shows the proper output, GitHub seems screwed somehow.

**Comment by angerman** [comment]
Ahh force push seems to have gotten the confusion away

**Comment by angerman** [comment]
> [!] we need to embed a git hash into the devx shell. Currently it's impossible to tell from which revision the specific shell was built.

I've implemented this one now in `main`.

**Comment by angerman** [comment]
Current status:
- windows failures: because we need to regenerate the devx containers, once hydra is done.
- linux failures: dynamic libraries are missing (need to find, and copy the .so's along). I did set the interpreter, hence the error messages are more meaningful now.

**Comment by angerman** [comment]
After discussing this with @hamishmack; we may come back to this for Darwin -> Windows, once that works again in haskell.nix.

**Pull request merged**
